### ISSUE TITLE
little problems

### ISSUE THREAD

**Issue by Rambo28456** [ZelGimi/industrialupgrade#131]
Hello, my English is bad, sorry for this translation.
In the mod version -
IndustrialUpgrade-1.12.2-2.4.0.5:
1. Improvement "Ejector" does not work.
2. Does not transmit energy from solar panels through wires.
3. Wires transfer power after re-entering the card.
4. Please make support for the mod "TATW", everything worked well on the version of the mod (IndustrialUpgrade-1.12.2-2.3.5). Crashes when entering the map. Crash Log -
[crash-2023-01-08_22.38.52-server.txt](https://github.com/ZelGimi/industrialupgrade/files/10369500/crash-2023-01-08_22.38.52-server.txt)

**Comment by ZelGimi** [comment]
1. Where exactly does it not work for you?
2-4. between 2.3.5 and 2.4, RC mods were released, in which their own energy transfer system was developed (more optimized). We know the problem with the transfer especially when the transition was abrupt from 2.3.5 to 2.4 or with some mods that are fixed in 2.4.0.6 (next patch).
4. There will be no support for tatw. This crash is on the side of tatw , not iu

**Comment by Rambo28456** [comment]
Advanced Combination Crusher does not push ores into the Ultimate Electric Furnace
![Снимок экрана (49)](https://user-images.githubusercontent.com/108591561/211253336-db26c3a2-5643-40d9-9e66-d6d8d4ddc715.png)

**Comment by Rambo28456** [comment]
With update 2.4.0.6, the problem with wires has not changed. The solar panel does not transfer energy to storage.
I also noticed that he stopped feeding the "Energy Receiver" from AE2
