### ISSUE TITLE
Explosion of machinery

### ISSUE THREAD

**Issue by NikitaZemlin** [ZelGimi/industrialupgrade#9]
Good afternoon!
I play on my private server and wanted to remove the voltage and explosion of mechanisms. In the IC2 config I have specified the parameters
enableEnetExplosions = true
enableEnetCableMeltdown = true
but it didn't help.

After that I noticed that all mechanisms inherent in IC2 are a new variant but in IU, which made me think that it is necessary to change the config of IU, however, I did not find anything suitable for me.

I'm playing on 1.12.2, thanks.

**Comment by MakandIv** [comment]
From the FAQ:

*Disabling any of the items is not recommended, as this may worsen the experience of playing with IU. Disable at your own risk.*
> How to disable machine explosions?
In the `industrialupgrade.cfg` configuration file, in the `"transformer mode"` section, find the line `B: "Enable explosion from mechanisms is on (if enable transformer mode) "` and change the value from `true` to `false`.
This only disables explosions. You still need to control your energy levels to play. Instead of explosions, machines will be disconnected from the power supply.
> How can I make it so that I don't have to control energy levels?
In the `industrialupgrade.cfg` configuration file, in the `"transformer mode"` section, find the line `B:"unchecking the tier"` and change the value from `false` to `true`.
> It just so happened that you need to disable the losses in the cables, how to do it?
In the `industrialupgrade.cfg` configuration file, in the `"transformer mode"` section, find the line `B:"Enable losing in cables is on (if enable transformer mode) "` and change the value from `true` to `false`.
> How to make the cables conduct an unlimited amount of energy, like in IC2 Experimental?
In the `industrialupgrade.cfg` configuration file, in the `"transformer mode"` section, find the line `B:"unlimiting the conduction of energy in the cable"` and change the value from `false` to `true`.
> How to disable all energy system complexities from IU by returning IC2?
In the `industrialupgrade.cfg` configuration file, in the `"transformer mode"` section, find the line `B:"Transformer mode"` and change the value from `true` to `false`. **Disables all previous items.**

The FAQ can be found on the Discord server.

**Comment by NikitaZemlin** [comment]
@MakandIv ty!
Also hint, I read the latest news about the conflict between IC2 and IU, am I correct that they are now two independent mods?

If so, I wanted to delete IC2 and stay only on IU, I like its crafts better. But a question - will I lose anything from the mechanics that are in IC2 but not in IU?

**Comment by MakandIv** [comment]
There are some losses in mechanics. There are no reactors yet, for example. All this will be gradually introduced, and some will have to be abandoned. 
You can follow the update on Discord.
